In [54]:
import torch
print(torch.__version__)

2.9.1+cpu


In [55]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [56]:
# using empty
a = torch.empty(2,3)

In [57]:
# check type
type(a)

torch.Tensor

In [58]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [59]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [60]:
# using rand
torch.rand(2,3)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [61]:
# use of seed
torch.rand(2,3)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [62]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [63]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [64]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [65]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [66]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

x.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [67]:
torch.empty_like(x)

tensor([[0, 1, 1],
        [1, 1, 1]])

In [68]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [69]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [70]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [71]:
# find data type
x.dtype


torch.int64

In [72]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [73]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [74]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [75]:
x = torch.rand(2,2)
print(x)

# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x * 3)

# division
print(x / 3)

# int division
print((x * 100)//3)

# mod
print(((x * 100)//3)%2)

# power
print(x**2)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])
tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise operation

In [76]:



a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

# add
print(a + b)

# sub
print(a - b)
# multiply

print(a * b)

# division
print(a / b)
# power

print(a ** b)

# mod
print(a % b)

c = torch.tensor([1, -2, 3, -4])

# abs
print(torch.abs(c))

# negative
print(torch.neg(c))

d = torch.tensor([1.9, 2.3, 3.7, 4.4])

# round
print(torch.round(d))

# ceil
print(torch.ceil(d))

# floor
print(torch.floor(d))

# clamp
print(torch.clamp(d, min=2, max=3))

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])
tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])
tensor([2., 2., 4., 4.])
tensor([2., 3., 4., 5.])
tensor([1., 2., 3., 4.])
tensor([2.0000, 2.3000, 3.0000, 3.0000])


### 3. Reduction operation

In [77]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(e)

# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along rows
print(torch.sum(e, dim=1))

# mean
print(torch.mean(e))

# mean along col
print(torch.mean(e, dim=0))

# median
print(torch.median(e))

# max and min
print(torch.max(e))
print(torch.min(e))

# product
print(torch.prod(e))

# standard deviation
print(torch.std(e))

# variance
print(torch.var(e))

# argmax
print(torch.argmax(e))

# argmin
print(torch.argmin(e))

tensor([[8., 0., 7.],
        [0., 0., 9.]])
tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])
tensor(4.)
tensor([4., 0., 8.])
tensor(0.)
tensor(9.)
tensor(0.)
tensor(0.)
tensor(4.4272)
tensor(19.6000)
tensor(5)
tensor(1)


### 4. Matrix operations


In [78]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

# matrix multiplcation
torch.matmul(f, g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


tensor([[ 87, 119],
        [ 65,  99]])

In [79]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [80]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [81]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

# determinant
torch.det(h)

tensor(-110.)

In [82]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [83]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

# greater than
print(i > j)

# less than
print(i < j)

# equal to
print(i == j)

# not equal to
print(i != j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### 6. Special functions

In [84]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [85]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [86]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [87]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [88]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [89]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [90]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [92]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [93]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [94]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [95]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [96]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [97]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [98]:
a = torch.rand(2,3)


In [99]:
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [100]:
b = a

In [101]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [102]:
a[0][0] = 0

In [103]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [104]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [105]:
id(a)

1712895251616

In [106]:
id(b)

1712895251616

In [107]:
b = a.clone()

In [108]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [109]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [110]:
a[0][0] = 10

a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [111]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [112]:
id(a)

1712895251616

In [113]:
id(b)

1712895262496